export const commentaryResearchMetadata = Object.freeze({
  knowledgeVersion: 'usabmx-national-2026-07-22-v4-full-field',
  method: 'aggregate-caption-and-broadcast-audio-context',
  officialChannel: 'https://www.youtube.com/@usabmxvideos/streams',
  broadcastAudioReference: 'https://www.youtube.com/watch?v=JRfRMptCE-I',
  coverageCutoff: '2026-07-22',
  indexedVideos: 166,
  indexedEventsByYear: Object.freeze({ 2025: 29, 2026: 20 }),
  analyzedCaptionTracks: 14,
  analyzedCaptionWords: 642_428,
  analyzedRaceCallSegments: 18_208,
  analyzedRaceAudioSections: 6,
  minimumGenerativeVocabularyTarget: 10_000,
  vocabularyStrategy: 'open-generative-lexicon',
  pendingCaptionTracks: 150,
  captionsDisabledBySource: 2,
  retainsFullTranscripts: false,
  retainsSourceAudio: false,
});

const eventLanguage = Object.freeze({
  'race-start': [
    'gate is down',
    'opening drive',
    'field is underway',
    'snaps out of the gate',
    'launches cleanly',
    'opening charge',
    'gets the jump',
    'powers away',
    'race comes alive',
    'clean release',
  ],
  'positions-established': [
    'out front',
    'early advantage',
    'the order settles',
    'in the two spot',
    'holding third',
    'running fourth',
    'working through traffic',
    'stays in the hunt',
    'keeps the race alive',
    'the full field',
    'running order',
  ],
  'lead-change': [
    'takes over',
    'moves to the front',
    'new leader',
    'coming back',
    'sweeps through',
    'finds a way past',
    'changes the order',
    'claims the advantage',
    'responds immediately',
    'door opens',
    'pressure pays off',
  ],
  'pedal-zone': [
    'rider giving chase',
    'pressure from behind',
    'through the rhythm section',
    'down the straight',
    'holds position',
    'keeps contact',
    'stays involved',
    'rides the pressure',
    'full-field battle',
    'keeps the line tidy',
    'works the course',
    'keeps the wheels moving',
    'order remains tight',
  ],
  'pro-set': [
    'commits to the Pro Set',
    'blue Pro line',
    'attacks the split',
    'chooses the bigger line',
    'takes the alternate route',
    'holds the advantage',
    'field responds',
    'line choice matters',
  ],
  'final-push': [
    'last straight',
    'final drive',
    'out front',
    'to the stripe',
    'last chance',
    'finishing charge',
    'still in the fight',
    'order on the line',
    'one final response',
    'nothing settled behind',
  ],
  finish: [
    'gets the win',
    'at the line',
    'to the stripe',
    'takes the race',
    'brings it home',
    'claims the victory',
    'wins the run',
    'field follows home',
  ],
});

const eventDelivery = Object.freeze({
  'race-start': 'Open promptly with an exciting gate-drop burst and carry that momentum into the opening charge.',
  'positions-established': 'Sound alert and invested; give the early order with lively forward motion.',
  'lead-change': 'Let the pass trigger a sharp, authentic surge of excitement.',
  'pedal-zone': 'Describe the rider battle and current track phase with urgent flow, not the mapped input zone.',
  'pro-set': 'Give the line choice a quick lift and connect it directly to the chase.',
  'final-push': 'Build powerful, controlled urgency through the last straight and toward the line.',
  finish: 'Celebrate the winner passionately, emphasize the name, and complete the result cleanly.',
});

export function commentaryGuideForEvent(eventKind) {
  const cues = eventLanguage[eventKind] ?? [];
  return [
    'Create fresh wording; these are short vocabulary cues, not quotations or required phrases.',
    `Relevant race-phase vocabulary: ${cues.join(', ')}.`,
    'These cues are not a closed phrase bank. Draw freely from a broad generative vocabulary and vary verbs, syntax, imagery, cadence, and focus while staying factual.',
    eventDelivery[eventKind] ?? 'Match the vocal energy to the live action.',
    'Lead with the live action, name riders only when the race facts identify them, and keep the call easy to understand at race speed.',
    'Cover the full running order across the race: leader, second, third, and fourth, plus pressure, passes, line choices, turns, rhythm, and the run to the line.',
    'Professional BMX calls use short clauses, occasional fragments, varied pacing, and high energy that surges naturally with passes and the run to the line.',
    'Do not imitate, identify, or reproduce the voice, catchphrases, or signature delivery of any source announcer.',
  ].join(' ');
}
