export const commentaryResearchMetadata = Object.freeze({
  knowledgeVersion: 'usabmx-national-2026-07-23-v5-generative-flow',
  method: 'aggregate-caption-terminology-and-event-driven-broadcast-flow',
  officialChannel: 'https://www.youtube.com/@usabmxvideos/streams',
  broadcastAudioReference: 'https://www.youtube.com/watch?v=JRfRMptCE-I',
  coverageCutoff: '2026-07-22',
  indexedVideos: 166,
  indexedEventsByYear: Object.freeze({ 2025: 29, 2026: 20 }),
  analyzedCaptionTracks: 14,
  analyzedCaptionWords: 642_428,
  analyzedRaceCallSegments: 18_208,
  analyzedRaceAudioSections: 6,
  minimumGenerativeVocabularyTarget: 10_000,
  vocabularyStrategy: 'open-generative-lexicon',
  pendingCaptionTracks: 150,
  captionsDisabledBySource: 2,
  retainsFullTranscripts: false,
  retainsSourceAudio: false,
});

const eventLanguage = Object.freeze({
  'race-start': [
    'gate is down',
    'opening drive',
    'field is underway',
    'snaps out of the gate',
    'launches cleanly',
    'opening charge',
    'gets the jump',
    'powers away',
    'race comes alive',
    'clean release',
  ],
  'positions-established': [
    'out front',
    'early advantage',
    'the order settles',
    'in the two spot',
    'holding third',
    'running fourth',
    'working through traffic',
    'stays in the hunt',
    'keeps the race alive',
    'the full field',
    'running order',
    'in the three spot',
    'the chase behind',
  ],
  'lead-change': [
    'takes over',
    'moves to the front',
    'new leader',
    'coming back',
    'sweeps through',
    'finds a way past',
    'changes the order',
    'claims the advantage',
    'responds immediately',
    'door opens',
    'pressure pays off',
    'out front now',
    'front changes hands',
    'drops into the two spot',
  ],
  'position-change': [
    'makes the pass',
    'moves up a spot',
    'finds a way through',
    'takes the position',
    'wheel-to-wheel',
    'running order changes',
    'gets the move done',
    'pressure turns into a pass',
    'battle stays alive',
    'bar to bar',
    'side by side',
    'responds to the move',
  ],
  'pedal-zone': [
    'rider giving chase',
    'pressure from behind',
    'through the rhythm section',
    'down the straight',
    'holds position',
    'keeps contact',
    'stays involved',
    'rides the pressure',
    'full-field battle',
    'keeps the line tidy',
    'works the course',
    'keeps the wheels moving',
    'order remains tight',
    'nothing between them',
    'coming back in the chase',
  ],
  'pro-set': [
    'commits to the Pro Set',
    'blue Pro line',
    'attacks the split',
    'chooses the bigger line',
    'takes the alternate route',
    'holds the advantage',
    'field responds',
    'line choice matters',
  ],
  'final-push': [
    'last straight',
    'final drive',
    'out front',
    'to the stripe',
    'last chance',
    'finishing charge',
    'still in the fight',
    'order on the line',
    'one final response',
    'nothing settled behind',
    'down the last straight',
    'one more charge',
  ],
  finish: [
    'gets the win',
    'at the line',
    'to the stripe',
    'takes the race',
    'brings it home',
    'claims the victory',
    'wins the run',
    'field follows home',
    'holds on at the stripe',
  ],
});

const eventDelivery = Object.freeze({
  'race-start': 'Open promptly with an exciting gate-drop burst and carry that momentum into the opening charge.',
  'positions-established': 'Sound alert and invested; give the early order with lively forward motion.',
  'lead-change': 'Let the pass trigger a sharp, authentic surge of excitement.',
  'position-change': 'React immediately to the pass with an energetic lift and make the new running order clear.',
  'pedal-zone': 'Describe the rider battle and current track phase with urgent flow, not the mapped input zone.',
  'pro-set': 'Give the line choice a quick lift and connect it directly to the chase.',
  'final-push': 'Build powerful, controlled urgency through the last straight and toward the line.',
  finish: 'Celebrate the winner passionately, emphasize the name, and complete the result cleanly.',
});

export function commentaryGuideForEvent(eventKind) {
  const cues = eventLanguage[eventKind] ?? [];
  return [
    'Create fresh wording; these are short vocabulary cues, not quotations or required phrases.',
    `Relevant race-phase vocabulary: ${cues.join(', ')}.`,
    'These cues are not a closed phrase bank. Draw freely from a broad generative vocabulary and vary verbs, syntax, imagery, cadence, and focus while staying factual.',
    eventDelivery[eventKind] ?? 'Match the vocal energy to the live action.',
    'Lead with the live action, name riders only when the race facts identify them, and keep the call easy to understand at race speed.',
    'Cover the full running order across the race: leader, second, third, and fourth, plus pressure, passes, line choices, turns, rhythm, and the run to the line.',
    'Professional BMX calls use short clauses, occasional fragments, varied pacing, and high energy that surges naturally with passes and the run to the line.',
    'Use a flexible live-race flow: establish the order, build pressure, call the decisive action, react to the change, then reset the running order. This is a structure, not a script.',
    'For close racing, tension should rise before a verified pass and release into a clear new-order call afterward. For quiet intervals, rotate attention through the field instead of repeating the leader.',
    'Useful USA BMX running-order language includes out front, the two spot, the three spot, coming back, bar to bar, side by side, down the straight, to the stripe, and gets the win. Use it selectively and generate original surrounding wording.',
    'Do not imitate, identify, or reproduce the voice, catchphrases, or signature delivery of any source announcer.',
  ].join(' ');
}
